baseURL = 'https://data-capsule.github.io/'
languageCode = 'en-us'
title = 'DataCapsule | UC Berkeley'
theme = "PaperMod"

enableRobotsTXT = true

[params]
disableSpecial1stPost = true
hideSummary = true


[params.homeInfoParams]
Title = "Data Capsules: Cryptographically hardened containers of data"
Content = """Alex Thomas, Eric Chen, Shubham Mishra, Prof. John D. Kubiatowicz


**Recent**: We presented Paranoid Statefule Lambda at SOSP 2023 poster session. [Poster Link](/files/sosp_2023_psl_poster.pdf)"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/data-capsule/"
